services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrations:
    image: migrations
    build:
      context: .
      dockerfile: migrations/Dockerfile  # Custom Dockerfile to handle migrations
    working_dir: /app
    volumes:
      - ./migrations:/app
    env_file:
      - migrations/.env
    depends_on:
      - db

  api:
    build:
      context: ./go-server
    volumes:
      - ./go-server:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - migrations

volumes:
  db_data:

networks:
  budget_network:
    driver: bridge