"""make actual expenses category required

Revision ID: 14ee733dea8f
Revises: 98d02fef7656
Create Date: 2026-08-01 17:39:13.142330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ee733dea8f'
down_revision: Union[str, None] = '98d02fef7656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actual_expenses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('actual_expenses_category_id_fkey', 'actual_expenses', type_='foreignkey')
    op.create_foreign_key(None, 'actual_expenses', 'expense_categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actual_expenses', type_='foreignkey')
    op.create_foreign_key('actual_expenses_category_id_fkey', 'actual_expenses', 'expense_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.alter_column('actual_expenses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###