"""from string to money

Revision ID: 7ff1be9357c4
Revises: d760baa77eeb
Create Date: 2026-08-30 14:42:59.073098

"""
import json
import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from cryptography.fernet import Fernet


# revision identifiers, used by Alembic.
revision: str = '7ff1be9357c4'
down_revision: Union[str, None] = 'd760baa77eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

DEFAULT_CURRENCY = "ARS"

# Tables holding an encrypted monetary column that previously stored only
# the encrypted amount as a plain string, now expected to store an
# encrypted JSON payload of {"amount": ..., "currency": ...}.
MONEY_TABLES = ("expected_expenses", "actual_expenses")


def _get_fernet() -> Fernet:
    from secrets import get_secrets_provider, SecretNotFoundError
    provider = get_secrets_provider()
    try:
        encryption_key = provider.get_secret("encryption_key")
    except SecretNotFoundError:
        encryption_key = os.environ.get("ENCRYPTION_KEY", "")
    if not encryption_key:
        raise RuntimeError(
            "Encryption key not configured. Set ENCRYPTION_KEY environment variable or provide via secrets provider."
        )
    return Fernet(encryption_key.encode())


def _decrypt(fernet: Fernet, ciphertext: str) -> str:
    if not ciphertext:
        return ""
    return fernet.decrypt(ciphertext.encode()).decode()


def _encrypt(fernet: Fernet, plaintext: str) -> str:
    if not plaintext:
        return ""
    return fernet.encrypt(plaintext.encode()).decode()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actual_expenses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('actual_expenses_category_id_fkey'), 'actual_expenses', type_='foreignkey')
    op.create_foreign_key(None, 'actual_expenses', 'expense_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Data migration: encrypted_amount used to store only the encrypted
    # plaintext amount (e.g. "123.45"). Re-encrypt it as a JSON payload
    # that also carries the currency, defaulting existing rows to ARS
    # (pesos argentinos).
    fernet = _get_fernet()
    bind = op.get_bind()

    for table in MONEY_TABLES:
        rows = bind.execute(
            sa.text(f"SELECT id, encrypted_amount FROM {table}")
        ).fetchall()

        for row_id, encrypted_amount in rows:
            if encrypted_amount is None:
                continue

            decrypted = _decrypt(fernet, encrypted_amount)

            try:
                existing = json.loads(decrypted)
            except (ValueError, TypeError):
                existing = None

            if isinstance(existing, dict) and "amount" in existing and "currency" in existing:
                # Already migrated to the money JSON format.
                continue

            money_payload = json.dumps({
                "amount": decrypted,
                "currency": DEFAULT_CURRENCY,
            })
            new_encrypted_amount = _encrypt(fernet, money_payload)

            bind.execute(
                sa.text(f"UPDATE {table} SET encrypted_amount = :value WHERE id = :id"),
                {"value": new_encrypted_amount, "id": row_id},
            )


def downgrade() -> None:
    # Reverse data migration: unwrap the JSON payload back to a plain
    # encrypted amount string, dropping the currency information.
    fernet = _get_fernet()
    bind = op.get_bind()

    for table in MONEY_TABLES:
        rows = bind.execute(
            sa.text(f"SELECT id, encrypted_amount FROM {table}")
        ).fetchall()

        for row_id, encrypted_amount in rows:
            if encrypted_amount is None:
                continue

            decrypted = _decrypt(fernet, encrypted_amount)

            try:
                money_data = json.loads(decrypted)
            except (ValueError, TypeError):
                money_data = None

            if not isinstance(money_data, dict) or "amount" not in money_data:
                # Already in the plain amount format.
                continue

            new_encrypted_amount = _encrypt(fernet, str(money_data["amount"]))

            bind.execute(
                sa.text(f"UPDATE {table} SET encrypted_amount = :value WHERE id = :id"),
                {"value": new_encrypted_amount, "id": row_id},
            )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actual_expenses', type_='foreignkey')
    op.create_foreign_key(op.f('actual_expenses_category_id_fkey'), 'actual_expenses', 'expense_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('actual_expenses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
