"""empty message

Revision ID: 98d02fef7656
Revises: cd7faf5348ef
Create Date: 2026-07-12 00:30:24.114380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d02fef7656'
down_revision: Union[str, None] = 'cd7faf5348ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expected_expenses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('expected_expenses_category_id_fkey'), 'expected_expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expected_expenses', 'expense_categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expected_expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expected_expenses_category_id_fkey'), 'expected_expenses', 'expense_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.alter_column('expected_expenses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
