"""add_group_invitations

Revision ID: cd7faf5348ef
Revises: a3b4c5d6e7f8
Create Date: 2026-06-15 23:33:25.399228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7faf5348ef'
down_revision: Union[str, None] = 'a3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_invitations',
    sa.Column('budgeting_group_id', sa.Integer(), nullable=False),
    sa.Column('inviter_user_id', sa.Integer(), nullable=False),
    sa.Column('accepted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'revoked', 'expired', name='invitationstatus'), server_default='pending', nullable=False),
    sa.Column('role', sa.String(length=50), server_default='member', nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['budgeting_group_id'], ['budgeting_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_invitations_external_id'), 'group_invitations', ['external_id'], unique=True)
    op.create_index('ix_group_invitations_group', 'group_invitations', ['budgeting_group_id'], unique=False)
    op.create_index('ix_group_invitations_status', 'group_invitations', ['status'], unique=False)
    op.create_index('ix_group_invitations_token', 'group_invitations', ['token'], unique=True)
    op.alter_column('user_preferences', 'external_id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('ix_user_preferences_external_id'), 'user_preferences', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_external_id'), table_name='user_preferences')
    op.alter_column('user_preferences', 'external_id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_group_invitations_token', table_name='group_invitations')
    op.drop_index('ix_group_invitations_status', table_name='group_invitations')
    op.drop_index('ix_group_invitations_group', table_name='group_invitations')
    op.drop_index(op.f('ix_group_invitations_external_id'), table_name='group_invitations')
    op.drop_table('group_invitations')
    # ### end Alembic commands ###
