"""partial unique indexes for soft delete

Revision ID: d760baa77eeb
Revises: 14ee733dea8f
Create Date: 2026-08-28 20:37:17.527945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd760baa77eeb'
down_revision: Union[str, None] = '14ee733dea8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actual_expenses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('actual_expenses_category_id_fkey'), 'actual_expenses', type_='foreignkey')
    op.create_foreign_key(None, 'actual_expenses', 'expense_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actual_expenses', type_='foreignkey')
    op.create_foreign_key(op.f('actual_expenses_category_id_fkey'), 'actual_expenses', 'expense_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('actual_expenses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
