"""initial_schema

Revision ID: ddd261308f71
Revises: 
Create Date: 2026-03-21 15:59:42.214221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd261308f71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgeting_groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgeting_groups_external_id'), 'budgeting_groups', ['external_id'], unique=True)
    op.create_table('users',
    sa.Column('external_provider_id', sa.String(length=255), nullable=False),
    sa.Column('auth_provider', sa.Enum('GOOGLE', 'GITHUB', 'LOCAL', name='authprovider'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_index(op.f('ix_users_external_provider_id'), 'users', ['external_provider_id'], unique=False)
    op.create_index('ix_users_provider_id', 'users', ['auth_provider', 'external_provider_id'], unique=True)
    op.create_table('budgets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('budgeting_group_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['budgeting_group_id'], ['budgeting_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_external_id'), 'budgets', ['external_id'], unique=True)
    op.create_index('ix_budgets_group_dates', 'budgets', ['budgeting_group_id', 'start_date', 'end_date'], unique=False)
    op.create_table('expense_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('budgeting_group_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['budgeting_group_id'], ['budgeting_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_categories_external_id'), 'expense_categories', ['external_id'], unique=True)
    op.create_index('ix_expense_categories_group_name', 'expense_categories', ['budgeting_group_id', 'name'], unique=True)
    op.create_table('participants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budgeting_group_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['budgeting_group_id'], ['budgeting_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_external_id'), 'participants', ['external_id'], unique=True)
    op.create_index('ix_participants_group_name', 'participants', ['budgeting_group_id', 'name'], unique=True)
    op.create_table('expected_expenses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('encrypted_amount', sa.String(length=1024), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expected_expenses_budget', 'expected_expenses', ['budget_id'], unique=False)
    op.create_index('ix_expected_expenses_category', 'expected_expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expected_expenses_external_id'), 'expected_expenses', ['external_id'], unique=True)
    op.create_table('user_participants',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_participants_external_id'), 'user_participants', ['external_id'], unique=True)
    op.create_index('ix_user_participants_participant', 'user_participants', ['participant_id'], unique=False)
    op.create_index('ix_user_participants_user', 'user_participants', ['user_id'], unique=False)
    op.create_index('ix_user_participants_user_participant', 'user_participants', ['user_id', 'participant_id'], unique=True)
    op.create_table('actual_expenses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('encrypted_amount', sa.String(length=1024), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('expected_expense_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expected_expense_id'], ['expected_expenses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_actual_expenses_budget', 'actual_expenses', ['budget_id'], unique=False)
    op.create_index('ix_actual_expenses_category', 'actual_expenses', ['category_id'], unique=False)
    op.create_index('ix_actual_expenses_date', 'actual_expenses', ['expense_date'], unique=False)
    op.create_index('ix_actual_expenses_expected', 'actual_expenses', ['expected_expense_id'], unique=False)
    op.create_index(op.f('ix_actual_expenses_external_id'), 'actual_expenses', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actual_expenses_external_id'), table_name='actual_expenses')
    op.drop_index('ix_actual_expenses_expected', table_name='actual_expenses')
    op.drop_index('ix_actual_expenses_date', table_name='actual_expenses')
    op.drop_index('ix_actual_expenses_category', table_name='actual_expenses')
    op.drop_index('ix_actual_expenses_budget', table_name='actual_expenses')
    op.drop_table('actual_expenses')
    op.drop_index('ix_user_participants_user_participant', table_name='user_participants')
    op.drop_index('ix_user_participants_user', table_name='user_participants')
    op.drop_index('ix_user_participants_participant', table_name='user_participants')
    op.drop_index(op.f('ix_user_participants_external_id'), table_name='user_participants')
    op.drop_table('user_participants')
    op.drop_index(op.f('ix_expected_expenses_external_id'), table_name='expected_expenses')
    op.drop_index('ix_expected_expenses_category', table_name='expected_expenses')
    op.drop_index('ix_expected_expenses_budget', table_name='expected_expenses')
    op.drop_table('expected_expenses')
    op.drop_index('ix_participants_group_name', table_name='participants')
    op.drop_index(op.f('ix_participants_external_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index('ix_expense_categories_group_name', table_name='expense_categories')
    op.drop_index(op.f('ix_expense_categories_external_id'), table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_index('ix_budgets_group_dates', table_name='budgets')
    op.drop_index(op.f('ix_budgets_external_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index('ix_users_provider_id', table_name='users')
    op.drop_index(op.f('ix_users_external_provider_id'), table_name='users')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_budgeting_groups_external_id'), table_name='budgeting_groups')
    op.drop_table('budgeting_groups')
    # ### end Alembic commands ###
